## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [1]:
import numpy as np

In [2]:
np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [8]:
n = 3
arr = list(np.arange(1, 4))
np.array(arr * n)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [13]:
n = 10
a = np.arange(1, n * 2, 2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [9]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [11]:
a = np.zeros((8,8), dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [15]:
n = 10
m = np.arange(n ** 2)
print((m // n + m % n).reshape(n, n))

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [10]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(11, 20).reshape(3, 3)
c = np.array([1, 2, 3])

print('Вектор на вектор:', np.dot(c, c))
print('Матрица на вектор:',np.dot(a, c))
print('Матрица на матрицу: \n',np.dot(a, b))

Вектор на вектор: 14
Матрица на вектор: [14 32 50]
Матрица на матрицу: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [14]:
m = np.arange(0, 1, 0.05)
s = np.sin(m)
c = np.cos(m)
a = np.vstack((s, c))
print(a)

[[0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
  0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
  0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
  0.78332691 0.8134155 ]
 [1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
  0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
  0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
  0.62160997 0.58168309]]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [88]:
a = np.random.uniform(-1,3,15).reshape(3,5)
print(a)

[[-0.62025928  0.54121778  0.60827945  0.42934181  0.34813864]
 [ 1.31150835  1.89828387  2.79303703  0.60175922  1.43911918]
 [ 2.85845858  0.91874141 -0.57128178  0.38095503  2.75408623]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [49]:
print('Сумма всех элементов = ',np.sum(a))
print('Сумма внутри строк = ',np.sum(a, axis = 1)) 
print('Сумма внутри столбцов = ',np.sum(a, axis = 0)) 
print('Среднее значение = ',np.mean(a, axis=1)) 
print('Дисперсия = ',np.var(a, axis=1)) 
print('Стандартное отклонение = ',np.std(a, axis=1)) 

Сумма всех элементов =  19.264305323897407
Сумма внутри строк =  [9.27320524 3.69014511 6.30095497]
Сумма внутри столбцов =  [4.58100815 3.42401266 5.56319671 2.35659901 3.3394888 ]
Среднее значение =  [1.85464105 0.73802902 1.26019099]
Дисперсия =  [0.21617774 1.18183736 1.74463815]
Стандартное отклонение =  [0.46494918 1.08712343 1.32084751]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [86]:
a = np.random.uniform(-1,3,15).reshape(3,5)
x = np.average(a, axis=-1)
y = np.sqrt(np.var(a, axis=-1, dtype=float))
print((a - x.reshape(len(x), 1)) / y.reshape(len(y), 1))

[[ 1.15432053  1.09313116 -0.03600024 -0.99159067 -1.21986078]
 [ 0.02760433  1.49141075  0.64994972 -1.09658972 -1.07237508]
 [-0.34562799 -0.50880619 -0.90431927  1.94174609 -0.18299264]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [78]:
a = np.random.uniform(-1,3,15).reshape(3,5).transpose()
a[a[:, 2].argsort()]

[[ 1.82058898 -0.60161229 -0.93011199]
 [ 0.3987786   2.50060843 -0.12041253]
 [-0.14718098  0.07839108  2.70819728]
 [-0.1178262   2.51103298  2.85695141]
 [ 0.16960007  0.79709724  2.94364875]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [18]:
a = np.random.uniform(-1,3,15).reshape(3,5)
b = a.dot(a.T)
c = a.T.dot(a)
print('В =',b)
print('C =',c)
# Обе матрицы квадратные. Они разных размеров: матрица В - 3х3, матрица С - 5х5

В = [[18.27935578  5.5704161  11.75765448]
 [ 5.5704161   8.632621    1.06634244]
 [11.75765448  1.06634244 16.66359745]]
C = [[10.63124461  8.53315246  9.27123186  2.5522537   1.22050287]
 [ 8.53315246  8.96777821  7.82306503  4.30084988  0.16122882]
 [ 9.27123186  7.82306503 10.76900386  5.10375103  5.31804884]
 [ 2.5522537   4.30084988  5.10375103  5.34457187  3.58389837]
 [ 1.22050287  0.16122882  5.31804884  3.58389837  7.86297568]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [19]:
print('Матрица В = ',np.trace(b))
print('Матрица C = ',np.trace(c))

Матрица В =  43.575574233461964
Матрица C =  43.575574233461964


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [90]:
print('Ранг матрицы А = ',np.linalg.matrix_rank(a),'\nМатрица не квадратная, поэтому детерминант и спектр матрицы A посчитать нельзя ')
print('Ранг матрицы В = ',np.linalg.matrix_rank(b),'\nДетерминант матрицы В = ',np.linalg.det(b))
w, v = np.linalg.eig(b)
print ("Собственные значения матрицы В = :\n", w)
print('Ранг матрицы C = ',np.linalg.matrix_rank(c),'\nДетерминант матрицы C = ',np.linalg.det(c))
w, v = np.linalg.eig(c)
print ("Собственные значения матрицы C = :", w)
#Ранги всех матриц одинаковые. Длины спектров равны размерностям матриц В и С.

Ранг матрицы А =  3 
Матрица не квадратная, поэтому детерминант и спектр матрицы A посчитать нельзя 
Ранг матрицы В =  3 
Детерминант матрицы В =  1037.9316394803532
Собственные значения матрицы В = :
 [30.33655995  3.52047703  9.71853725]
Ранг матрицы C =  3 
Детерминант матрицы C =  -1.3693285179669933e-28
Собственные значения матрицы C = : [ 3.03365600e+01  9.71853725e+00  1.81242970e-15  3.52047703e+00
 -1.21101395e-15]


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [69]:
np.random.seed(1032205148)
np.random.randint(9)

4

Аналитическое решение интеграла №4$: \frac{\pi}{4} \approx 0.78539816$

Аналитическое решение интеграла №9$: \frac{\pi}{2^\frac{3}{2}} \approx 1.11072073$

In [71]:
import math


def f4(x):
    return 1 / (x * (1 + np.log(x) ** 2))

def rectangle(f4, a, b, h):
    x = np.linspace(a, b - h, int((b - a) / h))
    y = h * f4(x)
    return np.sum(y)

def trapezoid(f4, a, b, h):
    x = np.linspace(a, b, int((b - a) / h) + 1)
    y = f4(x[0]) + 2 * np.sum(f4(x[1:-1])) + f4(x[-1])
    return y * h / 2

def simpson(f4, a, b, h):
    x = np.linspace(a, b, int((b - a) / h) + 1)
    y = f4(x[0]) + 4 * np.sum(f4(x[1:-1:2])) + 2 * np.sum(f4(x[2:-1:2])) + f4(x[-1])
    return y * h / 3

print('Метод прямоугольников для №4:', rectangle(f4, 1, math.e, 0.01))
print('Метод трапеций для №4:', trapezoid(f4, 1, math.e, 0.001))
print('Метод Симпсона для №4:', simpson(f4, 1, math.e, 0.0001))

Метод прямоугольников для №4: 0.7856870096432769
Метод трапеций для №4: 0.7852694163440457
Метод Симпсона для №4: 0.7853607609641667


In [67]:
def f9(x):
    return 1 / (np.sqrt(2 + 3 * x - 2 * x ** 2, where = x!=2))

def rectangle(f9, a, b, h):
    x = np.linspace(a, b - h, int((b - a) / h))
    y = h * f9(x)
    return np.sum(y)

def trapezoid(f9, a, b, h):
    x = np.linspace(a, b, int((b - a) / h) + 1)
    y = f9(x[0]) + 2 * np.sum(f9(x[1:-1])) + f9(x[-1])
    return y * h / 2

def simpson(f9, a, b, h):
    x = np.linspace(a, b, int((b - a) / h) + 1)
    y = f9(x[0]) + 4 * np.sum(f9(x[1:-1:2])) + 2 * np.sum(f9(x[2:-1:2])) + f9(x[-1])
    return y * h / 3

print('Метод прямоугольников для №9:', rectangle(f9, np.float64(3/4), 2, 0.01))
print('Метод трапеций для №9:', trapezoid(f9, np.float64(3/4), 2, 0.001))
print('Метод Симпсона для №9:', simpson(f9, np.float64(3/4), 2, 0.0001))

Метод прямоугольников для №9: 1.048221521865416
Метод трапеций для №9: 1.0902276150046217
Метод Симпсона для №9: 1.1051022196964917


 Чем меньше шаг интегрирования, тем точнее решение.